{% set name = "child" %}
{% set version = "18.08" %}
{% set build = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/childmodel/{{ name }}/archive/v{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: bfffd8bf8f71556d4c64c09ff8eed286daa6b8e0dfa702dd20fab6c4301ded07

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  run:
    - libgcc

test:
  commands:
    - child --help
    - child --version

build:
  number: {{ build }}

about:
  home: http://csdms.colorado.edu/wiki/Model:CHILD
  license: MIT
  summary: Landscape Evolution Model
  description: |
    CHILD computes the time evolution of a topographic surface z(x,y,t)
    by fluvial and hillslope erosion and sediment transport.
  doc_url: http://csdms.colorado.edu/wiki/Model:CHILD
  dev_url: https://github.com/childmodel/child
